local count = require("diffundo.count")

describe("count.normalize", function()
  it("treats an empty count as one", function()
    assert.are.equal("1", count.normalize(""))
    assert.are.equal("1", count.normalize(nil))
  end)

  it("keeps a plain number", function()
    assert.are.equal("2", count.normalize("2"))
  end)

  it("keeps a unit suffix", function()
    assert.are.equal("2f", count.normalize(" 2f "))
  end)

  it("rejects an unknown unit", function()
    assert.has_error(function()
      count.normalize("1w")
    end, "invalid count: 1w (expected a number, optionally followed by s, m, h, d or f)")
  end)

  it("rejects a negative number", function()
    assert.has_error(function()
      count.normalize("-3")
    end)
  end)
end)

describe("count.exact", function()
  it("keeps a plain number", function()
    assert.are.equal("3", count.exact("3"))
    assert.are.equal("0", count.exact(" 0 "))
  end)

  it("rejects an empty count", function()
    assert.has_error(function()
      count.exact("")
    end)
    assert.has_error(function()
      count.exact(nil)
    end)
  end)

  it("rejects a unit suffix", function()
    assert.has_error(function()
      count.exact("2f")
    end)
  end)

  it("rejects a negative number", function()
    assert.has_error(function()
      count.exact("-3")
    end)
  end)
end)
